---------------------------------------------------------------------------------------------------- flag

SELECT * FROM PWX.ORDER_REQUEST ORDER BY ORDER_CODE;
--DELETE FROM PWX.ORDER_REQUEST; 

SELECT * FROM PWX.ORDER_HEADER;  
	--DELETE FROM PWX.ORDER_HEADER;

SELECT * FROM ORDERREC;
	--DELETE FROM ORDERREC;

SELECT * FROM PLV.LINEREC WHERE ORDERNUMBER = '9230001';

--DELETE FROM PLV.LINEREC;

SELECT* FROM PWX.ORDER_LINE_REQUEST ;wHERE Orq_ID = '108082';
	--DELETE FROM PWX.ORDER_LINE;

SELECT * FROM PWX.ORDER_LINE_FULFILLMENT;

SELECT * FROM AUFTSTAT ;
	--DELETE FROM PLV.AUFTSTAT;

SELECT * FROM PWX.TRANSPORT_UNIT WHERE TUT_ID BETWEEN '131' AND '136';
	--DELETE FROM PWX.TRANSPORT_UNIT WHERE PROGRAM_CREATED = 'HCom.HCom';

----------------------------------------------------------------------------------------------------- SKU / BARCODE  sbu_id 114.065 sku_id 114065 sku_code AF3849

SELECT * FROM PWX.SKU ORDER BY SKU_CODE;
	--DELETE FROM PWX.SKU ; 
	
SELECT * FROM PWX.SKU_BUNDLE;																			 		 	
-- 	DELETE FROM PWX.SKU_BUNDLE; 		
	
SELECT * FROM PWX.SKU_BIN_TYPE;
	--DELETE FROM 
	
SELECT * FROM PWX.SKU_BARCODE; 					
	--DELETE FROM PWX.SKU_BARCODE;
	
SELECT * FROM PWX.SKU_LOCATION_MAP;
	--DELETE FROM PWX.SKU_LOCATION_MAP;

----------------------------------------------------------------------------------------------------- LOCATION

SELECT * FROM PWX.LOCATION; WHERE GEOCODE LIKE 'PB%';
	--DELETE FROM PWX.LOCATION;

SELECT * FROM PWX.LOCATION_GROUP; 									
	--DELETE FROM pWX.LOCATION_GROUP;

SELECT * FROM PWX.LOCATION_GROUP_MEMBER_DEF; 						
	--DELETE FROM PWX.LOCATION_GROUP_MEMBER_DEF;

SELECT * FROM PWX.LOCATION_GROUP_TYPE; 	

SELECT * FROM PWX.TRANSPORT_UNIT_TYPE;

SELECT * FROM PWX.TRANSPORT_UNIT_BIN_TYPE;

-- TABELA DE CANAIS DO PEMAT/A-FRAME
SELECT * FROM KANAL;-- ORDER BY CODE; 								
SELECT * FROM CHANNELS;WHERE GEOCODE = 'AF-2006';-- WHERE PRODNUMBER = 0000100956; 	 

-----------------------------------------------------------------------------------------------------

SELECT * FROM PWX.ORDER_HEADER OH INNER JOIN ORDER_LINE OL ON OH.OH_ID = OL.OH_ID;						--JOIN ORDER_HEADER COM ORDER_LINE (EM COMUM)
SELECT * FROM PWX.ORDER_REQUEST ORQ INNER JOIN ORDER_LINE_REQUEST OLRQ ON ORQ.ORQ_ID = OLRQ.ORQ_ID;		--JOIN DA ORDER_REQUEST COM ORDER_LINE_REQUEST (EM COMUM)
SELECT * FROM PWX.ORDERREC REC INNER JOIN LINEREC LREC ON REC.ORDERNUMBER = LREC.ORDERNUMBER; 			--JOIN DA ORDERREC COM A LINEREC (EM COMUM)

-----------------------------------------------------------------------------------------------------

SELECT SLM.SLM_ID, SKU.SKU_CODE, L.GEOCODE FROM SKU_LOCATION_MAP SLM INNER JOIN SKU ON SLM.SKU_ID = SKU.SKU_ID INNER JOIN LOCATION L ON L.L_ID = SLM.L_ID  ORDER BY GEOCODE DESC;  WHERE SLM.SKU_ID = 132308; -- JOIN SKU e GEOCODE
SELECT SLM.SLM_ID, SKU.SKU_CODE, L.GEOCODE FROM SKU_LOCATION_MAP SLM INNER JOIN SKU ON SLM.SKU_ID = SKU.SKU_ID INNER JOIN LOCATION L ON L.L_ID = SLM.L_ID WHERE GEOCODE LIKE '%P%' ORDER BY SKU_CODE DESC;
SELECT SLM.SLM_ID, SKU.SKU_CODE, L.GEOCODE FROM SKU_LOCATION_MAP SLM INNER JOIN SKU ON SLM.SKU_ID = SKU.SKU_ID INNER JOIN LOCATION L ON L.L_ID = SLM.L_ID WHERE GEOCODE LIKE '%AF%' ORDER BY SKU_CODE DESC;

--UPDATE TRANSPORT_UNIT SET TU_STATUS = 99 WHERE TU_CODE = '301428';

------------------------------------------------------------------------------------------------------

-- ORDER_HEADER COM ORDER_LINE
-- ORDER_REQUEST COM ORDER_LINE_REQUEST
-- ORDERREC COM LINEREC
-- SKU COM SKU_LOCATION_MAP E LOCATION
-- LOCAITON COM LOCATION_GROUP
	
-----------------------------------------------------------------------------------------------------

SELECT * FROM PWX.S7_STATION_CONFIG ORDER BY STATION_NAME;-- WHERE STATION_NAME = '%JPT2.2%' ;
SELECT * FROM PWX.S7_TYPICAL_DIRECTIONS; --RUS_2222

-----------------------------------------------------------------------------------------------------

SELECT * FROM PWX.MESSAGE_LOG ORDER BY MLOG_ID DESC;
	SELECT DISTINCT status FROM PWX.MESSAGE_LOG;

SELECT * FROM PLV.PBL_LINES;

SELECT * FROM PLV.PBL_MODULE;

SELECT * FROM YANBOG_USER_REG;

SELECT * FROM GLB_DOMAIN_KEY ORDER BY KEY;

SELECT * FROM PLV.PBL_ORDER_SQS;


-----------------------------------------------------------------------------------------------------

SELECT MAX(ORDER_CODE) FROM PWX.ORDER_REQUEST WHERE ORDER_CODE LIKE '999%'
SELECT SLM.SLM_ID, SKU.SKU_CODE, L.GEOCODE FROM SKU_LOCATION_MAP SLM INNER JOIN SKU ON SLM.SKU_ID = SKU.SKU_ID INNER JOIN LOCATION L ON L.L_ID = SLM.L_ID ORDER BY SKU_CODE
