SELECT * FROM PWX.GLB_DOMAIN_KEY ORDER BY KEY;
SELECT * FROM PWX.S7_TYPICAL_DIRECTIONS;

SELECT * FROM PLV.AUFTSTAT;
SELECT * FROM PLV.AUFTSTAT WHERE ORDERNUMBER = 10000;
SELECT * FROM PLV.LINEREC ;
SELECT * FROM PLV.LINEREC WHERE ORDERNUMBER = 9584;
SELECT * FROM PLV.ORDERREC ;
SELECT * FROM PLV.ORDERREC O JOIN PWX.ORDER_HEADER OH ON OH.ORDER_CODE = TO_CHAR(O.ORDERNUMBER);
SELECT * FROM PLV.ORDERREC WHERE ORDERNUMBER = 9584 ;
SELECT * FROM PWX.LOCATION_GROUP;
SELECT * FROM PWX.LOCATION_GROUP WHERE LG_ID = 100024;
SELECT * FROM PWX.ORDER_HEADER;
SELECT * FROM PWX.ORDER_HEADER WHERE ORDER_CODE = 10000;
SELECT * FROM PWX.ORDER_HEADER WHERE ORQ_ID = 124266;
SELECT * FROM PWX.ORDER_LINE;
SELECT * FROM PWX.ORDER_LINE WHERE OH_ID = 117356; 
SELECT * FROM PWX.ORDER_LINE_FULFILLMENT ;
SELECT * FROM PWX.ORDER_LINE_FULFILLMENT WHERE OL_ID = 226957;
SELECT * FROM PWX.ORDER_REQUEST ;
SELECT * FROM PWX.ORDER_REQUEST  WHERE ORDER_CODE = 10000;
SELECT * FROM PWX.OL_BIUR_STATUS;

-- RETORNA TODAS AS TABELAS
SELECT OWNER, TABLE_NAME FROM DBA_TABLES WHERE OWNER = 'PWX';
  
SELECT * FROM SKU_LOCATION_MAP WHERE SKU_ID LIKE '100001%' ;
  
SELECT * FROM LOCATION ORDER BY GEOCODE;

-- RETORNA TODOS GEOCODES 
SELECT GEOCODE FROM LOCATION ORDER BY GEOCODE;

-- RETORNA SKU_CODE | GEOCODE
SELECT SKU_CODE, GEOCODE FROM SKU , SKU_LOCATION_MAP SLM, LOCATION L WHERE SLM.L_ID = L.L_ID AND SKU.SKU_ID = SLM.SKU_ID  ORDER BY GEOCODE;

SELECT LG.LG_CODE, L.GEOCODE, SKU_CODE FROM LOCATION_GROUP_MEMBER_DEF LGMD, LOCATION_GROUP LG,LOCATION L,SKU_LOCATION_MAP SLM, SKU WHERE LGMD.L_ID = L.L_ID AND LGMD.LG_ID_IN = LG.LG_ID AND SLM.L_ID = L.L_ID AND SLM.SKU_ID = SKU.SKU_ID  AND LG_CODE LIKE 'PBL01%';

SELECT SKU_CODE, GEOCODE FROM SKU , SKU_LOCATION_MAP SLM, LOCATION L WHERE SLM.L_ID = L.L_ID AND SKU.SKU_ID = SLM.SKU_ID  ORDER BY GEOCODE;

SELECT COUNT(*) FROM LOCATION ORDER BY GEOCODE; 

SELECT LG.LG_CODE, L.GEOCODE, SKU_CODE FROM LOCATION_GROUP_MEMBER_DEF LGMD, LOCATION_GROUP LG,LOCATION L,SKU_LOCATION_MAP SLM, SKU WHERE LG_CODE LIKE 'PBL01%';

SELECT STATION_NAME, TECH_STATION_NAME, FP FROM S7_STATION_CONFIG ORDER BY FP;

SELECT * FROM S7_TYPICAL_DIRECTIONS;

--SELECT * FROM  S7_TYPICAL_DIRECTIONS;
--DESC S7_TYPICAL_DIRECTIONS;
--DESC ALL_KEYS
--SELECT STATION_NAME, TECH_STATION_NAME, FP FROM S7_STATION_CONFIG ORDER BY STATION_NAME ASC

UPDATE S7_STATION_CONFIG OUTER
SET FP = (
    SELECT RNUM FROM (
      SELECT STATION_NAME, ROW_NUMBER() OVER (ORDER BY STATION_NAME ASC)*3 RNUM 
      FROM S7_STATION_CONFIG) INNER
      WHERE INNER.STATION_NAME = OUTER.STATION_NAME);
      
SELECT * FROM S7_STATION_CONFIG ORDER BY FP;   
SELECT * FROM S7_STATION_CONFIG WHERE STATION_NAME LIKE 'PBLA2%';
SELECT * FROM S7_STATION_CONFIG WHERE STATION_NAME LIKE 'MS%';

SELECT * FROM S7_STATION_CONFIG WHERE STATION_NAME LIKE 'JPT%';
    
    UPDATE S7_STATION_CONFIG SET STATION_NAME = 'JPT02' WHERE STATION_NAME = 'PBLA21'
    
    UPDATE S7_STATION_CONFIG SET STATION_NAME = 'PBLA20' WHERE STATION_NAME = 'JPT02'
        
    UPDATE S7_STATION_CONFIG SET TECH_STATION_NAME = SUBSTR(TECH_STATION_NAME,0,8)||FP WHERE FP >= 100
    
    SELECT SUBSTR(TECH_STATION_NAME,0,8) FROM S7_STATION_CONFIG;
    
SELECT * FROM S7_STATION_CONFIG ORDER BY FP ASC;

COMMIT;

SELECT * FROM USER_OBJECTS; -- VAI MOSTRAR TODOS OBJETOS CRIADOS PELO PR�PRIO USU�RIO. 
SELECT * FROM ALL_OBJECTS; -- TODOS OBJETOS QUE O USU�RIO TEM ACESSO. 
SELECT * FROM ALL_TAB_COLUMNS; -- MOSTRA AS TABELAS E SUAS COLUNAS 
SELECT * FROM ALL_TABLES; -- TODAS TABELAS 
SELECT * FROM DBA_JOBS; -- TODOS JOBS DO BANCO 

SELECT * FROM USER_SOURCE WHERE TYPE IN('PROCEDURE','TRIGGER'); --ESSSA QUERY AQUI VOC� VAI VER OS OBJETOS PROCEDURES E TRIGGERS DO SEU OWNER.

SELECT OBJECT_NAME(PARENT_ID) AS TABELA,* FROM SYS.TRIGGERS WHERE OBJECT_NAME(PARENT_ID) = 'SUA_TABELA';

SELECT * FROM PWX.YANBOG_USER_REG;
SELECT * FROM PWX.YANBAL_UTILS;

SELECT * FROM ALL_TRIGGERS WHERE TABLE_NAME = 'YANBOG_USER_REG';
SELECT * FROM DBA_TRIGGERS WHERE TABLE_NAME = 'YANBOG_USER_REG';
SELECT * FROM USER_TRIGGERS WHERE TABLE_NAME = 'YANBOG_USER_REG';

