----------------------------------------------------------------------------------------------------- START ORDER

UPDATE PLV.ORDERREC SET STATE = 100 WHERE STATE = 1;
UPDATE PWX.ORDER_HEADER SET OH_STATUS = 5 WHERE OH_STATUS = 0;


--UPDATE PLV.AUFTSTAT SET STATUS = 0, SOLLGEW = 0, STUECK =0, LASTAUSST = NULL WHERE ORDERNUMBER = 446241  ;
--UPDATE PLV.LINEREC SET STATE = 0, MISSING = 16 WHERE ORDERNUMBER = 446241  ;
--UPDATE PLV.ORDERREC SET BOXNUMBER = NULL WHERE ORDERNUMBER= 446241;
--UPDATE PLV.ORDERREC SET STATE= 1 WHERE ORDERNUMBER = 446241  ;

--UPDATE PWX.ORDER_HEADER SET TU_ID = NULL WHERE OH_ID = 118175;
--UPDATE PWX.ORDER_REQUEST SET ORQ_STATUS = 10 WHERE ORQ_ID = 124018;
--UPDATE PWX.ORDER_HEADER SET OH_STATUS = 0 WHERE OH_ID = 118175; 
--UPDATE PWX.ORDER_LINE_REQUEST SET OLRQ_STATUS = 10 WHERE ORQ_ID =  124018;
--UPDATE PWX.ORDER_LINE SET OL_STATUS = 0, FULFILLED = 0 WHERE OH_ID = 118175;


--UPDATE PWX.TRANSPORT_UNIT_TYPE SET LENGTH = 380, HEIGHT = 150, WIDTH = 310, TUT_CODE = 'CARTON_1', DESCR = 'Bandeja 1' WHERE TUT_ID = 1; 

--DELETE FROM PWX.TRANSPORT_UNIT_TYPE WHERE TUT_CODE = 'CARTON_68';


