XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
									LOCATION_GROUP 
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100005, 'A01', 13, NULL, 0, 'T', 'A01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100010, 'A02', 13, NULL, 0, 'T', 'A02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100015, 'AFP01', 13, 3, 0, 'T', 'AFP01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100020, 'AFP02', 13, 3, 0, 'T', 'AFP02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100025, 'AFPA01', 10, NULL, 0, 'T', 'AFPA01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100030, 'AFPA02', 10, NULL, 0, 'T', 'AFPA02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100035, 'AIP01', 10, NULL, 0, 'T', 'AIP01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100040, 'AIP02', 10, NULL, 0, 'T', 'AIP02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100045, 'BAL01', 10, NULL, 0, 'T', 'BAL01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100050, 'BAL02', 10, NULL, 0, 'T', 'BAL02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100055, 'BAL03', 10, NULL, 0, 'T', 'BAL03');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100060, 'BAL04', 10, NULL, 0, 'T', 'BAL04');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100065, 'CHK01', 10, NULL, 0, 'T', 'CHK01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100070, 'CHK02', 10, NULL, 0, 'T', 'CHK02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100075, 'CHK03', 10, NULL, 0, 'T', 'CHK03');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100080, 'CHK04', 10, NULL, 0, 'T', 'CHK04');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100085, 'CHK05', 10, NULL, 0, 'T', 'CHK05');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100090, 'CHK06', 10, NULL, 0, 'T', 'CHK06');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100095, 'CHK07', 10, NULL, 0, 'T', 'CHK07');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100100, 'CHK08', 10, NULL, 0, 'T', 'CHK08');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100105, 'MANUAL_AREA', 10, NULL, 0, 'T', 'MANUAL_AREA');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100110, 'P01', 12, NULL, 0, 'F', 'please add description');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100115, 'P02', 12, NULL, 0, 'T', 'P02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100120, 'P03', 12, NULL, 0, 'T', 'P03');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100125, 'P04', 12, NULL, 0, 'T', 'P04');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100130, 'P05', 12, NULL, 0, 'T', 'P05');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100135, 'P06', 12, NULL, 0, 'T', 'P06');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100140, 'P07', 12, NULL, 0, 'T', 'P07');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100145, 'P08', 12, NULL, 0, 'T', 'P08');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100150, 'P09', 12, NULL, 0, 'T', 'P09');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100155, 'P10', 12, NULL, 0, 'T', 'P10');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100160, 'P11', 12, NULL, 0, 'T', 'P11');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100165, 'P12', 12, NULL, 0, 'T', 'P12');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100170, 'P13', 12, NULL, 0, 'T', 'P13');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100175, 'P14', 12, NULL, 0, 'T', 'P14');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100180, 'P15', 12, NULL, 0, 'T', 'P15');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100185, 'P16', 12, NULL, 0, 'T', 'P16');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100190, 'P17', 12, NULL, 0, 'T', 'P17');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100195, 'P18', 12, NULL, 0, 'T', 'P18');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100200, 'P19', 12, NULL, 0, 'T', 'P19');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100205, 'PBL-AREA-04-11', 6, NULL, 0, 'T', 'PBL-AREA-04-11');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100210, 'PBL-AREA-12-19', 6, NULL, 0, 'T', 'PBL-AREA-12-19');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100215, 'PBL-AREA-CAT', 6, NULL, 0, 'T', 'PBL-AREA-CAT');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100220, 'PBL-AREA-POP', 6, NULL, 0, 'T', 'PBL-AREA-POP');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100225, 'PBL-STATION-P01', 158, NULL, 0, 'T', 'PBL-STATION-P01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100230, 'PBL-STATION-P02', 158, NULL, 0, 'T', 'PBL-STATION-P02');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100235, 'PBL-STATION-P03', 158, NULL, 0, 'T', 'PBL-STATION-P03');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100240, 'PBL-STATION-P04', 158, NULL, 0, 'T', 'PBL-STATION-P04');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100245, 'PBL-STATION-P05', 158, NULL, 0, 'T', 'PBL-STATION-P05');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100250, 'PBL-STATION-P06', 158, NULL, 0, 'T', 'PBL-STATION-P06');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100255, 'PBL-STATION-P07', 158, NULL, 0, 'T', 'PBL-STATION-P07');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100260, 'PBL-STATION-P08', 158, NULL, 0, 'T', 'PBL-STATION-P08');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100265, 'PBL-STATION-P09', 158, NULL, 0, 'T', 'PBL-STATION-P09');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100270, 'PBL-STATION-P10', 158, NULL, 0, 'T', 'PBL-STATION-P10');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100275, 'PBL-STATION-P11', 158, NULL, 0, 'T', 'PBL-STATION-P11');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100280, 'PBL-STATION-P12', 158, NULL, 0, 'T', 'PBL-STATION-P12');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100285, 'PBL-STATION-P13', 158, NULL, 0, 'T', 'PBL-STATION-P13');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100290, 'PBL-STATION-P14', 158, NULL, 0, 'T', 'PBL-STATION-P14');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100295, 'PBL-STATION-P15', 158, NULL, 0, 'T', 'PBL-STATION-P15');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100300, 'PBL-STATION-P16', 158, NULL, 0, 'T', 'PBL-STATION-P16');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100305, 'PBL-STATION-P17', 158, NULL, 0, 'T', 'PBL-STATION-P17');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100310, 'PBL-STATION-P18', 158, NULL, 0, 'T', 'PBL-STATION-P18');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100315, 'PBL-STATION-P19', 158, NULL, 0, 'T', 'PBL-STATION-P19');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100320, 'SHP01', 10, NULL, 0, 'T', 'SHP01');
INSERT INTO LOCATION_GROUP (LG_ID, LG_CODE, LGT_ID, CTL_ID, NUMBER_OF_LOCS, TF_FIND_LOCATION, DESCRIPTION) VALUES ( 100001, 'S01', 9, 11, 0, 'F', 'please add description');

SELECT * FROM LOCATION_GROUP ORDER BY LG_ID;
--DELETE FROM LOCATION_GROUP;

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX